### ISSUE TITLE
Release 기준 커밋과 실제 바이너리의 소스코드 불일치.

### ISSUE THREAD

**Issue by SubroutineUserEX** [Riey/ezEmuera#1]
webp 호환성 작업 중 릴리즈 20190314의 커밋 0692b49585c7a0933404d2de24065c9558f5cffa 이 실제 Released 된 ezEmuera의 소스코드가 아님을 확인하였습니다.

해당 커밋의 'https://github.com/Riey/ezEmuera/blob/0692b49585c7a0933404d2de24065c9558f5cffa/Emuera/Program.cs' 에서는 EZTrans를 통한 번역을 진행하는 부분이 존재하지 않으며, Emuera 프로젝트 전체에서도 관련 코드를 찾아내지 못했습니다.

이후 커밋에서 부터는 "EZTrans.dll" 라이브러리가 아닌 "ezemuera_trans.dll"를 사용하고 있어 실제 Released 된 바이너리에 대한 소스코드가 전혀 존재하지 않습니다.

아래 목록은 현재까지 확인된 기준 커밋에 존재하지 않는 내용입니다.
- class MinorShift.Emuera.EzEmueraSetting
- method MinorShift.Emuera.InitEzEmuera
- method MinorShift.Emuera.ExitEzEmuera

실제 Released 된 바이너리와 커밋 상 소스코드가 다른 점에 따라 Release 바이너리에 악성 코드가 존재할 수 있다고 판단되며, 이에 대하여 개발자 분의 해명을 요구하는 바 입니다.

**Comment by Riey** [comment]
커밋 히스토리 보면 뭔일 있었는지 다 나오는데 내가 해명할게 뭐가 있습니까

그냥 지금 master랑 최신 릴리즈랑 버전이 안맞아요

https://github.com/Riey/ezEmuera/compare/v1824-0...master

**Comment by Riey** [comment]
죄송합니다 제가 내용을 잘못봤네요 예전에 올라와있는 코드는 전부 원본 코드고요 제가 바꾼건 ez.patch에 다 있고 그걸 git diff로 적용해서 컴파일 했습니다

**Comment by Riey** [comment]
더 질문 있으시면 이슈 다시 열어주세요
